AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function for automated S3 backup cleanup with retention policies

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket containing backups
    MinLength: 1
  
  RetentionConfigPath:
    Type: String
    Description: S3 path to retention config (s3://bucket/key) or JSON string
    MinLength: 1
  
  ScheduleExpression:
    Type: String
    Description: CloudWatch Events schedule expression for Lambda execution
    Default: cron(0 2 ? * 0 *)  # Sunday at 2 AM UTC
  
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11
    Tags:
      Project: backup-cleaner
      ManagedBy: SAM

Resources:
  BackupCleanerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'backup-cleaner-${Environment}'
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Description: Cleans up old S3 backups based on retention policies
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          RETENTION_CONFIG: !Ref RetentionConfigPath
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                - !Sub 'arn:aws:s3:::${BucketName}'
                - !Sub 'arn:aws:s3:::${BucketName}/*'
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub 'arn:aws:s3:::*'  # Allow reading config from any S3 bucket
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/backup-cleaner-${Environment}:*'
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Trigger backup cleanup on a schedule
            Enabled: true
  
  BackupCleanerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/backup-cleaner-${Environment}'
      RetentionInDays: 30

Outputs:
  BackupCleanerFunctionArn:
    Description: ARN of the Backup Cleaner Lambda function
    Value: !GetAtt BackupCleanerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  BackupCleanerFunctionName:
    Description: Name of the Backup Cleaner Lambda function
    Value: !Ref BackupCleanerFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
  
  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref BackupCleanerLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'

